from flask import Flask, render_template

app = Flask(__name__)


@app.route('/plot/')
def plot():
    from pandas_datareader import data
    import datetime
    from bokeh.plotting import figure, show, output_file
    from bokeh.embed import components
    #CDN == content delivery network
    from bokeh.resources import CDN

    start_var = datetime.datetime(2015, 11,1)
    end_var = datetime.datetime(2016,3,10)
    df1 = data.DataReader(name='GOOG', data_source='yahoo', start=start_var, end=end_var)

    def inc_dec(c,o):
        if c > o:
            value='Increase'
        elif c < o:
            value='Decrease'
        else:
            value='Equal'
        return value
    #adds columns to the table so we can position the rectangle
    #candlestick with more precision
    df1['Status'] = [inc_dec(c,o) for c, o in zip(df1.Close,df1.Open)]
    df1['Middle'] = (df1.Open + df1.Close)/2
    df1['Height'] = abs(df1.Close - df1.Open)
    #makes the outer box and stores it in a variable
    graph = figure(x_axis_type='datetime', width=1000, height=300, sizing_mode='scale_width')
    graph.title.text = 'Candlestick Chart'
    graph.grid.grid_line_alpha = 0.3

    #variable for the amount of milliseconds in 12 hrs
    hours_12 = 12*60*60*1000

    #x coordinate, y coordinate, x coordinate, y coordinate
    graph.segment(df1.index, df1.High, df1.index, df1.Low, color='Black')
    #x coordinate, y coordinate, width, height
    graph.rect(df1.index[df1.Status=='Increase'], df1.Middle[df1.Status=='Increase'], hours_12,
        df1.Height[df1.Status=='Increase'], fill_color='#CCFFFF', line_color='black')
    graph.rect(df1.index[df1.Status=='Decrease'], df1.Middle[df1.Status=='Decrease'], hours_12,
        df1.Height[df1.Status=='Decrease'], fill_color='#FF3333', line_color='black')

    #assigns the items of the tuple generated by components
    #the srcipt for javascript and its corressponding html
    script1, div1 = components(graph)
    cdn_js = CDN.js_files[0]
    return render_template('plot.html',
    script1=script1,
    div1=div1,
    cdn_js = cdn_js)
@app.route('/')
def home():
    return render_template('home.html')

@app.route('/about')
def about():
    return render_template('about.html')

if __name__ == '__main__':
    app.run(debug=True)